# Pandas

In [1]:
import pandas as pd

In [2]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep = '\s+', header = None)

In [3]:
df_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [6]:
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [16]:
df_data['weight_0'] = 1     # weight값 추가
df_data = df_data.drop("MEDV", axis = 1)     # Y값 제거
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,1

In [19]:
df_data.shape

(506, 14)

In [20]:
df_matrix = df_data.as_matrix() # 506 x 14
weight_vector = np.random.random_sample((14, 1))   # 14 x 1

In [22]:
weight_vector

array([[ 0.55765907],
       [ 0.5165692 ],
       [ 0.12256141],
       [ 0.88893851],
       [ 0.03502704],
       [ 0.41511912],
       [ 0.93516834],
       [ 0.45909436],
       [ 0.13020126],
       [ 0.64386061],
       [ 0.70440074],
       [ 0.71578883],
       [ 0.96317343],
       [ 0.01061242]])

In [25]:
df_matrix.dot(weight_vector)

array([[ 565.5778861 ],
       [ 541.15240254],
       [ 516.98846919],
       [ 490.63415355],
       [ 502.49870042],
       [ 504.28198354],
       [ 581.56743037],
       [ 616.83478706],
       [ 623.38682954],
       [ 598.26670596],
       [ 613.58024937],
       [ 598.87114126],
       [ 555.16715519],
       [ 568.83325777],
       [ 579.85825221],
       [ 563.01795712],
       [ 529.76330341],
       [ 586.2485287 ],
       [ 470.80348626],
       [ 574.22706036],
       [ 600.28993281],
       [ 596.50518503],
       [ 606.95039552],
       [ 613.92195783],
       [ 604.85899699],
       [ 532.07416874],
       [ 587.41959124],
       [ 538.08325057],
       [ 597.46955456],
       [ 584.62456538],
       [ 586.52378506],
       [ 594.93406902],
       [ 488.94712537],
       [ 582.07186008],
       [ 507.10789032],
       [ 555.81113422],
       [ 537.26336599],
       [ 530.20357693],
       [ 518.52348927],
       [ 527.63170763],
       [ 519.94112363],
       [ 452.64588016],
       [ 455.33842613],
       [ 464.7803749 ],
       [ 494.43236456],
       [ 494.22724501],
       [ 497.60718329],
       [ 548.31855498],
       [ 571.86328983],
       [ 526.81541817],
       [ 524.8607858 ],
       [ 536.06693933],
       [ 495.15356948],
       [ 498.25304666],
       [ 705.15979802],
       [ 520.96214988],
       [ 587.91770398],
       [ 557.53107311],
       [ 531.12760004],
       [ 554.16160607],
       [ 574.51697484],
       [ 588.9252459 ],
       [ 571.38601226],
       [ 550.77393107],
       [ 513.86756083],
       [ 581.51279383],
       [ 599.11103722],
       [ 560.06443728],
       [ 579.6915678 ],
       [ 572.11296651],
       [ 504.2274438 ],
       [ 512.45422122],
       [ 509.18896445],
       [ 499.93594547],
       [ 571.09876885],
       [ 601.41290417],
       [ 624.86257922],
       [ 605.85766251],
       [ 615.28356021],
       [ 602.71786582],
       [ 534.17944913],
       [ 569.59414711],
       [ 534.1621109 ],
       [ 543.94547739],
       [ 516.15722642],
       [ 517.41019639],
       [ 515.59832412],
       [ 521.42425345],
       [ 561.69702892],
       [ 539.61708221],
       [ 542.21462054],
       [ 549.89276164],
       [ 548.62628216],
       [ 524.49097903],
       [ 574.3801457 ],
       [ 512.14431124],
       [ 551.73034429],
       [ 555.27149035],
       [ 515.55267788],
       [ 544.25360185],
       [ 634.20192946],
       [ 625.10008859],
       [ 408.505877  ],
       [ 644.64128593],
       [ 644.56695752],
       [ 655.51432456],
       [ 654.35752367],
       [ 638.03599917],
       [ 653.10057094],
       [ 647.89740373],
       [ 612.65068906],
       [ 666.0514007 ],
       [ 681.51869877],
       [ 686.31875998],
       [ 663.49748267],
       [ 640.95529142],
       [ 657.53052005],
       [ 666.12032044],
       [ 621.92409212],
       [ 650.76353515],
       [ 499.01789197],
       [ 504.20016889],
       [ 516.19881673],
       [ 521.59170268],
       [ 519.42908615],
       [ 513.95549662],
       [ 514.121677  ],
       [ 689.86638305],
       [ 694.53420036],
       [ 693.59857767],
       [ 690.76894574],
       [ 691.14146442],
       [ 681.96537414],
       [ 685.18270849],
       [ 600.32153994],
       [ 694.11569514],
       [ 677.54907341],
       [ 691.41274277],
       [ 695.85946628],
       [ 696.58941769],
       [ 691.58706259],
       [ 713.94527158],
       [ 681.95870665],
       [ 681.18583044],
       [ 680.89316618],
       [ 521.5055382 ],
       [ 507.87197766],
       [ 675.27856315],
       [ 647.60264722],
       [ 638.72872528],
       [ 648.54908737],
       [ 627.55207096],
       [ 616.94385705],
       [ 572.05949544],
       [ 612.0690574 ],
       [ 433.84617035],
       [ 444.16429456],
       [ 632.98494478],
       [ 630.00735177],
       [ 638.63392459],
       [ 612.4214948 ],
       [ 632.33517663],
       [ 651.56157781],
       [ 648.17650992],
       [ 657.5807008 ],
       [ 546.44784285],
       [ 636.13256981],
       [ 526.14934566],
       [ 590.9977584 ],
       [ 614.14546842],
       [ 588.72238279],
       [ 629.50740524],
       [ 588.04214158],
       [ 577.83036298],
       [ 562.17206178],
       [ 523.57678877],
       [ 542.96912904],
       [ 565.49220186],
       [ 563.9831827 ],
       [ 485.31659445],
       [ 510.36030019],
       [ 492.67087154],
       [ 514.75572235],
       [ 520.58002451],
       [ 518.58434048],
       [ 495.71120832],
       [ 477.72532627],
       [ 622.70330564],
       [ 601.83384379],
       [ 622.09955647],
       [ 592.57589378],
       [ 609.38896389],
       [ 604.17805907],
       [ 514.48299917],
       [ 510.16220022],
       [ 537.09729402],
       [ 588.82102032],
       [ 564.96560175],
       [ 591.8242287 ],
       [ 629.699736  ],
       [ 619.32437996],
       [ 607.94819942],
       [ 584.30541028],
       [ 526.02196334],
       [ 522.38105022],
       [ 513.05110196],
       [ 540.35704063],
       [ 561.96947558],
       [ 541.05906348],
       [ 598.28011111],
       [ 582.78497168],
       [ 587.18328376],
       [ 543.9774659 ],
       [ 513.23276286],
       [ 484.73942961],
       [ 528.31406475],
       [ 542.97205019],
       [ 566.07141141],
       [ 585.46390674],
       [ 575.14080778],
       [ 589.52885166],
       [ 605.78500485],
       [ 579.00981389],
       [ 583.32220147],
       [ 569.5132678 ],
       [ 572.50589838],
       [ 577.96757829],
       [ 563.60775248],
       [ 506.54886198],
       [ 512.1445065 ],
       [ 561.94402938],
       [ 562.98005387],
       [ 564.45243754],
       [ 557.92510552],
       [ 545.12839565],
       [ 553.80452253],
       [ 576.36508739],
       [ 567.71744981],
       [ 522.34129549],
       [ 548.66309857],
       [ 569.38740533],
       [ 582.5449447 ],
       [ 554.77351586],
       [ 508.22072071],
       [ 595.24086491],
       [ 606.99730011],
       [ 566.11772529],
       [ 598.41864305],
       [ 568.60255033],
       [ 549.95469659],
       [ 546.60751421],
       [ 526.8188988 ],
       [ 532.08880536],
       [ 542.03276636],
       [ 580.56958586],
       [ 572.62298002],
       [ 533.19563583],
       [ 560.56018403],
       [ 570.2971804 ],
       [ 575.47002337],
       [ 561.79505299],
       [ 563.62816305],
       [ 563.63583714],
       [ 575.90955127],
       [ 565.93329561],
       [ 543.95269227],
       [ 563.24123683],
       [ 540.58635033],
       [ 526.96285841],
       [ 524.25711775],
       [ 502.99891542],
       [ 478.685867  ],
       [ 517.9087763 ],
       [ 508.98284   ],
       [ 521.79492651],
       [ 529.7834341 ],
       [ 534.3665253 ],
       [ 515.3672646 ],
       [ 523.61029618],
       [ 484.69422605],
       [ 507.57966433],
       [ 486.27021231],
       [ 486.75507737],
       [ 500.09130625],
       [ 557.13840114],
       [ 559.11159197],
       [ 502.8810931 ],
       [ 555.12488656],
       [ 568.98886578],
       [ 531.67878883],
       [ 532.36023203],
       [ 532.53831521],
       [ 529.37625974],
       [ 514.28240216],
       [ 538.336549  ],
       [ 524.39899352],
       [ 541.09294355],
       [ 558.57558631],
       [ 571.46686159],
       [ 564.47474226],
       [ 614.45451758],
       [ 577.89887712],
       [ 547.82857529],
       [ 548.59220273],
       [ 505.93354139],
       [ 522.97179345],
       [ 536.26232239],
       [ 535.57398083],
       [ 580.63148567],
       [ 579.51112245],
       [ 513.5212279 ],
       [ 553.88596547],
       [ 593.90042149],
       [ 581.33289612],
       [ 588.85312621],
       [ 582.27129228],
       [ 590.04633404],
       [ 581.3474677 ],
       [ 570.66235181],
       [ 565.96455531],
       [ 544.96386937],
       [ 546.50340451],
       [ 543.22654231],
       [ 565.63004838],
       [ 532.68972864],
       [ 505.87231364],
       [ 522.49998081],
       [ 542.60606129],
       [ 602.05233721],
       [ 586.49521721],
       [ 597.66738667],
       [ 552.62832331],
       [ 520.81398682],
       [ 485.43547905],
       [ 486.60825619],
       [ 489.1203161 ],
       [ 501.46041606],
       [ 513.31905498],
       [ 491.14329101],
       [ 500.42835688],
       [ 512.24222414],
       [ 552.38343166],
       [ 632.19566633],
       [ 629.36009735],
       [ 594.44085025],
       [ 578.56398001],
       [ 569.09462095],
       [ 603.12811137],
       [ 554.3420842 ],
       [ 574.46156408],
       [ 588.68480869],
       [ 621.21732612],
       [ 622.29350035],
       [ 501.44721885],
       [ 582.12410754],
       [ 572.80108441],
       [ 836.2843747 ],
       [ 833.25983332],
       [ 828.09864502],
       [ 822.40623438],
       [ 812.66949917],
       [ 804.06186296],
       [ 826.00680613],
       [ 804.98072932],
       [ 792.16816989],
       [ 796.12787458],
       [ 778.5149154 ],
       [ 658.67875921],
       [ 819.27218776],
       [ 818.6378673 ],
       [ 831.07071029],
       [ 821.46350523],
       [ 798.22660562],
       [ 868.29039735],
       [ 875.1578188 ],
       [ 851.58724839],
       [ 829.80143849],
       [ 854.28831594],
       [ 861.76716925],
       [ 857.9299754 ],
       [ 888.19337949],
       [ 857.75974486],
       [ 856.9095725 ],
       [ 857.13971586],
       [ 781.47629101],
       [ 866.15090666],
       [ 869.47848809],
       [ 862.398615  ],
       [ 849.10838621],
       [ 852.66202796],
       [ 845.07672323],
       [ 820.93790873],
       [ 857.32024886],
       [ 841.93664373],
       [ 847.53522248],
       [ 846.21667288],
       [ 847.65080248],
       [ 848.88323501],
       [ 879.82977289],
       [ 800.73984815],
       [ 868.99762193],
       [ 856.89794829],
       [ 839.47437295],
       [ 858.16593344],
       [ 816.67009623],
       [ 880.51608678],
       [ 843.22478686],
       [ 800.90604124],
       [ 797.73974551],
       [ 700.93591078],
       [ 585.08522574],
       [ 598.7587614 ],
       [ 608.76812179],
       [ 731.13189015],
       [ 668.88372491],
       [ 603.01813183],
       [ 583.3031891 ],
       [ 665.98711132],
       [ 617.87722804],
       [ 586.78554713],
       [ 794.25812901],
       [ 788.9705224 ],
       [ 762.56426041],
       [ 559.62769171],
       [ 541.73837318],
       [ 578.7906329 ],
       [ 547.17015354],
       [ 573.90413407],
       [ 618.98783066],
       [ 613.23561954],
       [ 613.96854224],
       [ 623.18720599],
       [ 607.33431714],
       [ 624.8049017 ],
       [ 635.25719286],
       [ 647.88011709],
       [ 584.37666107],
       [ 585.98002028],
       [ 623.66915541],
       [ 850.77299619],
       [ 851.88956026],
       [ 843.41525364],
       [ 847.80806696],
       [ 846.06770137],
       [ 744.27215499],
       [ 600.53762135],
       [ 790.42298504],
       [ 841.8285735 ],
       [ 851.08712436],
       [ 784.55877209],
       [ 559.6568104 ],
       [ 818.52022424],
       [ 833.08422822],
       [ 835.24274257],
       [ 568.46485096],
       [ 589.69831647],
       [ 562.7006341 ],
       [ 550.64746347],
       [ 745.38608176],
       [ 833.16694347],
       [ 737.74781723],
       [ 831.26426777],
       [ 831.19802383],
       [ 831.52956917],
       [ 814.71617709],
       [ 752.02403898],
       [ 565.79273061],
       [ 800.58058778],
       [ 808.69459439],
       [ 810.71061822],
       [ 833.13279951],
       [ 834.86180997],
       [ 819.94482189],
       [ 797.70686216],
       [ 815.33491322],
       [ 786.56032825],
       [ 844.00846662],
       [ 825.0979259 ],
       [ 837.26768489],
       [ 829.188441  ],
       [ 810.76997455],
       [ 814.78152073],
       [ 817.80229054],
       [ 783.22891355],
       [ 771.28422648],
       [ 791.81120472],
       [ 825.88500987],
       [ 793.67225146],
       [ 865.96612737],
       [ 840.33301719],
       [ 827.12470906],
       [ 868.33176328],
       [ 854.45183602],
       [ 616.99646968],
       [ 608.00753258],
       [ 596.40957388],
       [ 643.58957856],
       [ 634.85702581],
       [ 628.61915563],
       [ 637.35320651],
       [ 643.47966061],
       [ 550.6152034 ],
       [ 560.37496837],
       [ 570.7434478 ],
       [ 567.54657814],
       [ 563.11703614]])

# Numpy

In [7]:
import numpy as np

In [8]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])

In [14]:
weight_vector.T.dot(x_vector)  # T : transpose, dot : 벡터 곱(결과값은 scalar)

array([[12]])